apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra

resources:
- ../../base
- ../../../../k8s/mysql/base
- ingress.yaml

images:
- name: 10.10.0.190:32000/infra-orch-studio
  newName: 10.10.0.190:32000/infra-orch-studio
  newTag: "83236b3"
- name: 10.10.0.190:32000/infra-orch-web
  newName: 10.10.0.190:32000/infra-orch-web
  newTag: "94d19ab"

replicas:
  - name: infra-orch-api
    count: 2
  - name: infra-orch-runner
    count: 1
  - name: infra-orch-web
    count: 2
