apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra

resources:
- ../../base
- ../../../../k8s/mysql/base
- ingress.yaml

images:
- name: registry.example.invalid/infra-orch-studio
  newName: registry.example.invalid/infra-orch-studio
  newTag: "ecee893"
- name: registry.example.invalid/infra-orch-web
  newName: registry.example.invalid/infra-orch-web
  newTag: "b48d17c-subpath"

replicas:
  - name: infra-orch-api
    count: 2
  - name: infra-orch-runner
    count: 1
  - name: infra-orch-web
    count: 2

patches:
- target:
    kind: ConfigMap
    name: infra-orch-runtime
  patch: |-
    - op: add
      path: /data/SESSION_COOKIE_SECURE
      value: "true"
