apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra

resources:
  - ../../base
  - ../../../../k8s/mysql/base

images:
  - name: registry.example.invalid/infra-orch-studio
    newName: registry.example.invalid/infra-orch-studio
    newTag: dev
  - name: registry.example.invalid/infra-orch-web
    newName: registry.example.invalid/infra-orch-web
    newTag: dev

replicas:
  - name: infra-orch-api
    count: 1
  - name: infra-orch-runner
    count: 1
  - name: infra-orch-web
    count: 1

patches:
  - path: web-service-nodeport.yaml
