apiVersion: v1
kind: Service
metadata:
  name: infra-orch-mysql
  labels:
    app.kubernetes.io/name: infra-orch-mysql
spec:
  selector:
    app.kubernetes.io/name: infra-orch-mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
