apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: infra-orch-mysql
  labels:
    app.kubernetes.io/name: infra-orch-mysql
spec:
  serviceName: infra-orch-mysql
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: infra-orch-mysql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: infra-orch-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - name: mysql
              containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: infra_orch
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: infra-orch-mysql
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: infra-orch-mysql
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: infra-orch-mysql
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
