apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infra

resources:
  - namespace.yaml
  - ../../k8s/mysql/base
  - secret-admin.example.yaml
  - secret-openstack.example.yaml
  - workdirs-pvc.yaml
  - api-service.yaml
  - api-deployment.yaml
  - runner-deployment.yaml
  - web-service.yaml
  - web-deployment.yaml
