apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-orch-web
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-orch-web
  template:
    metadata:
      labels:
        app: infra-orch-web
    spec:
      containers:
        - name: web
          image: 10.10.0.190:32000/infra-orch-web:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
