# OpenStack clouds secret used by API/Runner.
apiVersion: v1
kind: Secret
metadata:
  name: openstack-clouds
  labels:
    app.kubernetes.io/name: openstack-clouds
type: Opaque
stringData:
  clouds.yaml: |
    clouds:
      exporter-internal:
        region_name: RegionOne
        identity_api_version: 3
        interface: internal
        identity_interface: internal
        auth:
          auth_url: http://192.168.219.121:5000/v3
          username: admin
          password: "lsu95080$"
          project_name: admin
          user_domain_name: Default
          project_domain_name: Default
        endpoint_overrides:
          identity: http://192.168.219.121:5000/v3
          compute: http://192.168.219.121:8774/v2.1
          network: http://192.168.219.121:9696
          image: http://192.168.219.121:9292
          volumev3: http://192.168.219.121:8776/v3
          placement: http://192.168.219.121:8778
