apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: infra-orch-workdirs
  labels:
    app.kubernetes.io/name: infra-orch-workdirs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
